version: v1
kind: kubernetes
application: Potato Facts
targets:
  staging:
    account: armory-hosted-services-prod-agent
    namespace: armory-hosted-services-staging
    strategy: basic
manifests:
  - path: build/manifests/staging-manifests.yaml
    targets: [ "staging" ]
strategies:
  basic:
    canary:
      steps:
        - setWeight:
            weight: 50
        - pause:
            untilApproved: true