## Workflow variables
env:
  applicationName: sandbox

###
#
# On a release, build, bake, publish container
#
###
name: Build, Bake, and Publish Container

on:
  release:
    types: [released]

jobs:
  build-and-publish-container:
    name: Build Application, Bake, and Publish Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Login to Artifactory
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }} armory-docker-local.jfrog.io
        shell: bash

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.18.1'

      - name: Configure git for private modules
        run: git config --global url."https://x-access-token:${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Build & Push
        env:
          REGISTRY: index.docker.io
          REGISTRY_ORG: armory
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          make build-linux docker push

  scan-image:
    name: CVE Image Scan
    needs:
      - build-and-publish-container
    runs-on: ubuntu-latest
    steps:
      - name: Run Security Scan
        uses: armory-io/aquasec-scan-action@v0.0.8
        with:
          url: https://aquasec.armory.io
          registry: Artifactory
          username: ${{ secrets.AQUA_USER }}
          password: ${{ secrets.AQUA_PASSWORD }}
          image: armory/${{ env.applicationName }}:${{ github.event.release.tag_name }}
