## Workflow variables
env:
  applicationName: sandbox

###
#
# On a release, build, bake, publish container
#
###
name: Build, Bake, and Publish Container

on:
  release:
    types: [released]

jobs:
  build-and-publish-container:
    name: Build Application, Bake, and Publish Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Login to Docker Hub
        run: |
          docker login -u '${{ secrets.DOCKER_HUB_USER }}' -p '${{ secrets.DOCKER_HUB_PASS }}'
        shell: bash

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.19'

      - name: Build & Push
        env:
          REGISTRY: index.docker.io
          REGISTRY_ORG: armory
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          make build-linux docker push
