###
#
# Deploy an image tag.
# This job is separated out so that it can be triggered manually with any imageTag, new or old.
#
###
name: Deploy With Armory

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'The image tag to deploy'
        required: true

jobs:
  deploy:
    name: Generate Manifests and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.18.1'

      - name: Configure git for private modules
        run: git config --global url."https://x-access-token:${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Manifests
        env:
          IMAGE_TAG: "${{ github.event.inputs.imageTag }}"
        run: |
          make render-manifests

      - name: Upload Manifests
        uses: actions/upload-artifact@v2
        with:
          name: manifests
          path: build/manifests

      - name: Deploy
        uses: armory/cli-deploy-action@main
        with:
          clientId: ${{ secrets.ARMORY_CLOUD_PROD_CLIENT_ID }}
          clientSecret: ${{ secrets.ARMORY_CLOUD_PROD_CLIENT_SECRET }}
          path-to-file: "/infrastructure/armory/standard-deployment.yaml"
