###
#
# On pull_request creation/updates run the checks and submit to sonarqube
#
###
name: Pull Request Analysis

on: [ pull_request ]

jobs:
  pra:
    name: Pull Request Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.19'

      - name: Configure git for private modules
        run: git config --global url."https://x-access-token:${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      - uses: armory-io/infra-github-actions/golang-analyze-and-submit-to-sonar@master
        with:
          github_token: ${{ secrets.ARMORY_PLATFORM_GITHUB_PAT_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          check_command: make api-docs check
          go-version: '1.19'
